import { Member } from "@src/types";

export const members: Member[] = [
  {
    id: "yteraoka",
    name: "yteraoka",
    role: "SRE",
    bio: "ojisan",
    avatarSrc: "/avatars/yteraoka.jpeg",
    sources: ["https://blog.1q77.com/index.xml", "https://qiita.com/yteraoka/feed", "https://medium.com/feed/@yteraoka", "https://zenn.dev/yteraoka/feed"],
    includeUrlRegex: "",
    twitterUsername: "yteraoka",
    githubUsername: "yteraoka",
    websiteUrl: "https://blog.1q77.com/",
  },
  {
    id: "tozastation",
    name: "tozastation",
    role: "SRE",
    bio: "tarako_chan",
    avatarSrc: "/avatars/tozastation.jpg",
    sources: ["https://qiita.com/tozastation/feed", "https://tozastation.hashnode.dev/rss.xml", "https://zenn.dev/tozastation/feed"],
    includeUrlRegex: "",
    twitterUsername: "tozastation",
    githubUsername: "tozastation",
    websiteUrl: "https://github.com/tozastation",
  },
  {
    id: "kyohmizu",
    name: "kyohmizu",
    role: "SRE",
    bio: "mizumoto",
    avatarSrc: "/avatars/kyohmizu.png",
    sources: ["https://kyohmizu.hatenablog.com/feed", "https://qiita.com/kyohmizu/feed"],
    includeUrlRegex: "",
    twitterUsername: "kyohmizu",
    githubUsername: "kyohmizu",
    websiteUrl: "https://profile.kyohmizu.com/",
  },
  {
    id: "nwiizo",
    name: "nwiizo",
    role: "Software Developer",
    bio: "The Passionate Programmer",
    avatarSrc: "/avatars/nwiizo.jpeg",
    sources: ["https://syu-m-5151.hatenablog.com/feed", "https://zenn.dev/nwiizo/feed", "https://speakerdeck.com/nwiizo.rss"],
    includeUrlRegex: "",
    twitterUsername: "nwiizo",
    githubUsername: "nwiizo",
    websiteUrl: "https://nwiizo.github.io/",
  },
  {
    id: "skikkh",
    name: "skikkh",
    role: "SRE",
    bio: "skikkh",
    avatarSrc: "/avatars/skikkh.jpeg",
    sources: ["https://qiita.com/skikkh/feed"],
    includeUrlRegex: "",
    twitterUsername: "skikkh",
    githubUsername: "skikkh",
    websiteUrl: "",
  },
  {
    id: "toshikish",
    name: "toshikish",
    role: "SRE",
    bio: "Toshiki Shimomura",
    avatarSrc: "/avatars/toshikish.png",
    sources: ["https://toshikish.hateblo.jp/feed", "https://zenn.dev/toshikish/feed", "https://qiita.com/toshikish/feed"],
    includeUrlRegex: "",
    twitterUsername: "",
    githubUsername: "toshikish",
    websiteUrl: "",
  },
  {
    id: "Sreake",
    name: "Sreake",
    role: "",
    bio: "This Is The Sreake Section Blog.",
    avatarSrc: "/avatars/sreake.png",
    sources: ["https://sreake.com/feed/"],
    includeUrlRegex: "blog",
    excludeUrlRegex: "event",
    twitterUsername: "SreakeJ",
    githubUsername: "",
    websiteUrl: "https://sreake.com",
  },
  {
    id: "Reckoner",
    name: "Reckoner",
    role: "",
    bio: "This Is The Reckoner Section Blog.",
    avatarSrc: "/avatars/reckoner.png",
    sources: [],
    includeUrlRegex: "blog",
    excludeUrlRegex: "event",
    twitterUsername: "reckoner_japan",
    githubUsername: "",
    websiteUrl: "https://reckoner.io/",
  },
  {
    id: "tez",
    name: "Takuya Tezuka",
    role: "JB",
    bio: "tez",
    avatarSrc: "/avatars/tezuka.jpeg",
    sources: ["https://qiita.com/TT_Private/feed", "https://speakerdeck.com/takuyatezuka.rss"],
    includeUrlRegex: "qiita.com/TT_Private",
    twitterUsername: "tt0603",
    githubUsername: "taku-tez",
    websiteUrl: "https://www.wantedly.com/id/takuya_tezuka",
  },
  {
    id: "sosan01",
    name: "Soichiro Tsuchida",
    role: "SRE",
    bio: "sosan",
    avatarSrc: "/avatars/sosan01.png",
    sources: [],
    includeUrlRegex: "",
    twitterUsername: "",
    githubUsername: "sosan01",
    websiteUrl: "",
  },
  {
    id: "atsuya0",
    name: "Atsuya Tsukada",
    role: "SRE",
    bio: "human",
    avatarSrc: "/avatars/atsuya0.jpg",
    sources: ["https://zenn.dev/tayusa/feed", "https://qiita.com/atsuya0/feed"],
    includeUrlRegex: "",
    twitterUsername: "",
    githubUsername: "atsuya0",
    websiteUrl: "https://github.com/atsuya0",
  },
  {
    id: "masasuzu",
    name: "SUZUKI, Masashi",
    role: "SRE",
    bio: "yasetai",
    avatarSrc: "/avatars/masasuzu.png",
    sources: ["https://blog.masasuzu.net/feed", "https://speakerdeck.com/masasuzu.rss"],
    includeUrlRegex: "",
    twitterUsername: "masasuz",
    githubUsername: "masasuzu",
    websiteUrl: "https://masasuzu.net",
  },
  {
    id: "kiyos",
    name: "Kyohei Saito",
    role: "SRE",
    bio: "haraheri",
    avatarSrc: "/avatars/kiyos.jpeg",
    sources: ["https://zenn.dev/kyohei_saito/feed"],
    includeUrlRegex: "",
    twitterUsername: "kiyo_12_07",
    githubUsername: "kiyo-s",
    websiteUrl: "",
  },
  {
    id: "mos914",
    name: "Yu Kaneko",
    role: "SRE",
    bio: "koke",
    avatarSrc: "/avatars/mos914.png",
    sources: ["https://qiita.com/dirtymosschan/feed"],
    includeUrlRegex: "",
    twitterUsername: "",
    githubUsername: "mos914",
    websiteUrl: "",
  },
  {
    id: "unvavo",
    name: "nobu",
    role: "SRE",
    bio: "nobu",
    avatarSrc: "/avatars/nobu.png",
    sources: [],
    includeUrlRegex: "",
    twitterUsername: "unvavo",
    githubUsername: "unvavo",
    websiteUrl: "",
  },
  {
    id: "hiroki-hasegawa",
    name: "長谷川 広樹",
    role: "なんらかのエンジニア",
    bio: "顔画像は著作権フリーですのでどうぞ",
    avatarSrc: "/avatars/hirokihasegawa.png",
    sources: ["https://hiroki-hasegawa.hatenablog.jp/feed", "https://speakerdeck.com/hiroki_hasegawa.rss"],
    includeUrlRegex: "",
    twitterUsername: "Hiroki__IT",
    githubUsername: "hiroki-it",
    websiteUrl: "https://hiroki-it.github.io/tech-notebook/",
  },
  {
    id: "kaisato",
    name: "Kai Sato",
    role: "SRE",
    bio: "domo",
    avatarSrc: "/avatars/kaisato.png",
    sources: [],
    includeUrlRegex: "",
    twitterUsername: "KAI21441756",
    githubUsername: "kaitexio",
    websiteUrl: "",
  },
  {
    id: "ysakurai",
    name: "Yusuke Sakurai",
    role: "SRE",
    bio: "ysakurai",
    avatarSrc: "/avatars/ysakurai.jpg",
    sources: ["https://qiita.com/ys1/feed"],
    includeUrlRegex: "",
    twitterUsername: "",
    githubUsername: "saku3",
    websiteUrl: "",
  },
  {
    id: "tayakun",
    name: "Soichiro Taya",
    role: "SRE",
    bio: "tayakun",
    avatarSrc: "/avatars/tayakun.png",
    sources: ["https://qiita.com/tayakun/feed"],
    includeUrlRegex: "",
    twitterUsername: "",
    githubUsername: "tayatamn",
    websiteUrl: "",
  },
  {
    id: "SatohJohn",
    name: "SatohJohn",
    role: "Software Developer",
    bio: "SatohJohn",
    avatarSrc: "/avatars/satohjohn.png",
    sources: ["https://qiita.com/satohjohn/feed", "https://zenn.dev/satohjohn/feed"],
    includeUrlRegex: "",
    twitterUsername: "satohjohn",
    githubUsername: "satohjohn",
    websiteUrl: "",
  },
  {
    id: "bayobayo0324",
    name: "bayobayo0324",
    role: "back/front/app Engineer",
    bio: "osake daisuki",
    avatarSrc: "/avatars/bayobayo0324.jpeg",
    sources: ["https://qiita.com/bayobayo0324/feed"],
    includeUrlRegex: "",
    twitterUsername: "",
    githubUsername: "bayobayo0324",
    websiteUrl: "",
  },
  {
    id: "myamamoto",
    name: "myamamoto",
    role: "SRE",
    bio: "human",
    avatarSrc: "/avatars/myamamoto.jpeg",
    sources: ["https://zenn.dev/ureuzy/feed"],
    includeUrlRegex: "",
    twitterUsername: "ureuzy",
    githubUsername: "ureuzy",
    websiteUrl: "",
  },
  {
    id: "seno",
    name: "seno",
    role: "DBRE",
    bio: "seno",
    avatarSrc: "/avatars/seno.jpeg",
    sources: ["https://zenn.dev/nedoko_dok0dko/feed"],
    includeUrlRegex: "",
    twitterUsername: "",
    githubUsername: "senohirona",
    websiteUrl: "",
  },
  {
    id: "sakama",
    name: "sakama",
    role: "SRE",
    bio: "homo sapiens",
    avatarSrc: "/avatars/sakama.jpeg",
    sources: [],
    includeUrlRegex: "",
    twitterUsername: "",
    githubUsername: "junichiro-sakama",
    websiteUrl: "",
  },
  {
    id: "stakamura",
    name: "Shohei Takamura",
    role: "SRE",
    bio: "SRE",
    avatarSrc: "/avatars/stakamura.jpg",
    sources: ["https://zenn.dev/hakushou41/feed"],
    includeUrlRegex: "",
    twitterUsername: "hakushou41",
    githubUsername: "hakushou41",
    websiteUrl: "",
  },
  {
    id: "toVersus",
    name: "Tsubasa Nagasawa",
    role: "SRE",
    bio: "lazy programmer",
    avatarSrc: "/avatars/toVersus.png",
    sources: ["https://qiita.com/toVersus/feed", "https://zenn.dev/toversus/feed"],
    includeUrlRegex: "",
    twitterUsername: "toversus26",
    githubUsername: "toVersus",
    websiteUrl: "",
  },
  {
    id: "raba-jp",
    name: "Hiroki Sakuraba",
    role: "Software Developer",
    bio: "meow",
    avatarSrc: "/avatars/raba-jp.jpg",
    sources: ["https://zenn.dev/raba_jp/feed"],
    includeUrlRegex: "",
    twitterUsername: "",
    githubUsername: "raba-jp",
    websiteUrl: "",
  },
  {
    id: "ixsakra",
    name: "Ryosuke Sakurai",
    role: "SRE",
    bio: "ganbarumasu 'w'",
    avatarSrc: "/avatars/ixsakra.jpg",
    sources: [],
    includeUrlRegex: "",
    twitterUsername: "",
    githubUsername: "",
    websiteUrl: "",
  },
  {
    id: "nnaka2992",
    name: "NAKADATE Naoki",
    role: "DBRE",
    bio: "what on the earth is Database?",
    avatarSrc: "/avatars/nnaka2992.jpg",
    sources: ["https://nnaka2992.hatenablog.com/feed", "https://zenn.dev/nnaka2992/feed"],
    includeUrlRegex: "",
    twitterUsername: "",
    githubUsername: "",
    websiteUrl: "https://nnaka2992.hatenablog.com/",
  },
  {
    id: "satoken",
    name: "satoken",
    role: "SRE",
    bio: "How do you like Wednesday?",
    avatarSrc: "/avatars/satoken.jpg",
    sources: ["https://zenn.dev/satoken/feed"],
    includeUrlRegex: "",
    twitterUsername: "",
    githubUsername: "",
    websiteUrl: "",
  },
  {
    id: "bells17",
    name: "bells17",
    role: "Software Engineer",
    bio: "Software Engineer",
    avatarSrc: "/avatars/bells17.jpeg",
    sources: ["https://zenn.dev/bells17/feed", "https://medium.com/feed/@bells17", "https://speakerdeck.com/bells17.rss"],
    includeUrlRegex: "",
    twitterUsername: "bells17_",
    githubUsername: "bells17",
    websiteUrl: "https://bells17.io/",
  },
  {
    id: "hide-1",
    name: "Shuichi Inoue",
    role: "long-term internship student",
    bio: "I want to become a strong engineer :)",
    avatarSrc: "/avatars/hide-1.jpg",
    sources: ["https://sreake.com/blog/config-connectortest/feed", "https://sreake.com/blog/kubernetes-operation-with-chatgpt/feed", "https://sreake.com/blog/kubernetes-operation-with-chatgpt4/feed", "https://sreake.com/blog/chatgpt-slack-integration/feed"],
    includeUrlRegex: "",
    twitterUsername: "19MU50",
    githubUsername: "hide-1",
    websiteUrl: "",
  },
  {
    id: "yuu0w0yuu",
    name: "Yutaro Shirayama",
    role: "SRE",
    bio: "( ˘ω˘ )",
    avatarSrc: "/avatars/shirayama.jpg",
    sources: ["https://zenn.dev/yuu0w0yuu/feed"],
    includeUrlRegex: "",
    twitterUsername: "yuu0w0yuu",
    githubUsername: "yuu0w0yuu",
    websiteUrl: "",
  },
  {
    id: "gawingowin",
    name: "Araki Shogo",
    role: "long-term internship student",
    bio: "born 2 be engineer",
    avatarSrc: "/avatars/araki-icon.jpg",
    sources: [],
    includeUrlRegex: "",
    twitterUsername: "GawinGowin",
    githubUsername: "GawinGowin",
    websiteUrl: "",
  },
  {
    id: "nomadblacky",
    name: "Takumi Kadowaki",
    role: "Software Engineer @ Reckoner",
    bio: "Scala / Observability",
    avatarSrc: "/avatars/nomadblacky.jpg",
    sources: ["https://zenn.dev/nomadblacky/feed", "https://speakerdeck.com/nomadblacky.rss"],
    includeUrlRegex: "",
    twitterUsername: "nomadblacky",
    githubUsername: "NomadBlacky",
    websiteUrl: "",
  },
  {
    id: "kobuchi",
    name: "Shu Kobuchi",
    role: "Software Developer",
    bio: "mammalian",
    avatarSrc: "/avatars/kobuchi.jpeg",
    sources: ["https://shu-kob.hateblo.jp/feed", "https://speakerdeck.com/shukob.rss"],
    includeUrlRegex: "",
    twitterUsername: "shu_kob",
    githubUsername: "shu-kob",
    websiteUrl: "",
  },
  {
    id: "kojake_300",
    name: "Yuki Iwasaki",
    role: "SRE",
    bio: "Splatoon",
    avatarSrc: "/avatars/yuki_iwasaki.png",
    sources: ["https://qiita.com/kojake_300/feed", "https://zenn.dev/kojake_300/feed","https://speakerdeck.com/kojake_300.rss"],
    includeUrlRegex: "",
    twitterUsername: "kojake_300",
    githubUsername: "",
    websiteUrl: "",
  },
  {
    id: "kurita",
    name: "Kurita Keigo",
    role: "long-term internship student",
    bio: "I want to enginner the reliablity of the site",
    avatarSrc: "/avatars/kurita.jpg",
    sources: ["https://kechigon.hatenablog.com/feed"],
    includeUrlRegex: "",
    twitterUsername: "kechigongon",
    githubUsername: "kechigon",
    websiteUrl: "https://www.wantedly.com/id/keigo_kurita_e",
  },
  {
    id: "kaita-nakamura",
    name: "Kaita Nakamura",
    role: "SRE",
    bio: "kaita",
    avatarSrc: "/avatars/kaitanakamura.jpg",
    sources: ["https://zenn.dev/z63d/feed"],
    includeUrlRegex: "",
    twitterUsername: "z63d_",
    githubUsername: "z63d",
    websiteUrl: "",
  },
  {
    id: "komiyama5380",
    name: "MASARU Komiyama",
    role: "PMO",
    bio: "SRE!!!",
    avatarSrc: "/avatars/komiyama5380.jpg",
    sources: ["https://zenn.dev/komiyama/feed"],
    includeUrlRegex: "",
    twitterUsername: "",
    githubUsername: "komiyama5380",
    websiteUrl: "",
  },
  {
    id: "moz-sec",
    name: "Kobayashi Shun",
    role: "long-term internship student",
    bio: "I am a graduate student in Kyoto",
    avatarSrc: "/avatars/kobayashi.png",
    sources: ["https://moz-security.hatenablog.com/feed","https://zenn.dev/moz_sec/feed","https://speakerdeck.com/moz_sec_.rss"],
    includeUrlRegex: "",
    twitterUsername: "moz_sec_",
    githubUsername: "moz-sec",
    websiteUrl: "https://moz-sec.com/",
  },
  {
    id: "melanmeg",
    name: "Naoya Yamamoto",
    role: "SRE",
    bio: "konpeko~",
    avatarSrc: "/avatars/melanmeg.png",
    sources: ["https://zenn.dev/melanmeg/feed","https://speakerdeck.com/melanmeg.rss"],
    includeUrlRegex: "",
    twitterUsername: "melanmeg",
    githubUsername: "melanmeg",
    websiteUrl: "https://lit.link/melanmeg",
  },
  {
    id: "atusy",
    name: "Atsushi Yasumoto",
    role: "Software Developer",
    bio: "loves programming",
    avatarSrc: "/avatars/atusy.jpg",
    sources: ["https://blog.atusy.net/index.xml"],
    includeUrlRegex: "",
    twitterUsername: "Atsushi776",
    githubUsername: "atusy",
    websiteUrl: "https://blog.atusy.net/",
  },
  {
    id: "yyamada",
    name: "Yunosuke Yamada",
    avatarSrc: "/avatars/yyamada.jpg",
    role: "Full Stack Engineer",
    bio: "筋トレ / LLM / Webアプリケーション",
    source: ["https://zenn.dev/kimitsu/feed"],
    githubUsername: "YunosukeY",
    twitterUsername: "east_k1mitsu",
    websiteUrl: "https://linktr.ee/kimitsu",
  }
].sort((a, b) => (a.id < b.id ? -1 : 1));
